version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_postgres_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # S3
  s3:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9002:9000"
    volumes:
      - minio_dev_data:/data
    command: server /data

  # Bot
  bot:
    build: .
    environment:
      ENVIRONMENT: dev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dev_postgres_db
      DB_USER: dev_postgres_user
      DB_PASSWORD: dev_postgres_password
      S3_ENDPOINT: http://minio_dev:9000
      S3_BUCKET: myapp-dev
    depends_on:
      - postgres
      - s3

volumes:
  postgres_dev_data:
  minio_dev_data: